export default {
    // Chapeau
    "hat_1": require("images/character/hat_1.png"),
    "hat_2": require("images/character/hat_2.png"),
    "hat_3": require("images/character/hat_3.png"),
    "hat_4": require("images/character/hat_4.png"),
    "hat_5": require("images/character/hat_5.png"),
    "hat_6": require("images/character/hat_6.png"),
    "hat_7": require("images/character/hat_7.png"),
    "hat_8": require("images/character/hat_8.png"),
    "hat_man_1": require("images/character/hat_man_1.png"),
    "hat_woman_1": require("images/character/hat_woman_1.png"),
    "hat_woman_2": require("images/character/hat_woman_2.png"),

    // Visage
    "face_1": require("images/character/face_1.png"),
    "face_2": require("images/character/face_2.png"),
    "face_3": require("images/character/face_3.png"),
    "face_man_1": require("images/character/face_man_1.png"),
    "face_man_2": require("images/character/face_man_2.png"),
    "face_man_3": require("images/character/face_man_3.png"),
    "face_man_4": require("images/character/face_man_4.png"),
    "face_man_5": require("images/character/face_man_5.png"),
    "face_man_6": require("images/character/face_man_6.png"),
    "face_man_7": require("images/character/face_man_7.png"),
    "face_man_8": require("images/character/face_man_8.png"),
    "face_man_9": require("images/character/face_man_9.png"),
    "face_man_10": require("images/character/face_man_10.png"),
    "face_man_11": require("images/character/face_man_11.png"),
    "face_man_12": require("images/character/face_man_12.png"),
    "face_man_13": require("images/character/face_man_13.png"),
    "face_man_14": require("images/character/face_man_14.png"),
    "face_man_15": require("images/character/face_man_15.png"),
    "face_man_16": require("images/character/face_man_16.png"),
    "face_man_17": require("images/character/face_man_17.png"),
    "face_woman_1": require("images/character/face_woman_1.png"),
    "face_woman_2": require("images/character/face_woman_2.png"),
    "face_woman_3": require("images/character/face_woman_3.png"),
    "face_woman_4": require("images/character/face_woman_4.png"),
    "face_woman_5": require("images/character/face_woman_5.png"),
    "face_woman_6": require("images/character/face_woman_6.png"),
    "face_woman_7": require("images/character/face_woman_7.png"),
    "face_woman_8": require("images/character/face_woman_8.png"),
    "face_woman_9": require("images/character/face_woman_9.png"),
    "face_woman_10": require("images/character/face_woman_10.png"),
    "face_woman_11": require("images/character/face_woman_11.png"),
    "face_woman_12": require("images/character/face_woman_12.png"),
    "face_woman_13": require("images/character/face_woman_13.png"),
    "face_woman_14": require("images/character/face_woman_14.png"),

    // Veste
    "jacket_man_1": require("images/character/jacket_man_1.png"),
    "jacket_man_2": require("images/character/jacket_man_2.png"),
    "jacket_man_3": require("images/character/jacket_man_3.png"),
    "jacket_man_4": require("images/character/jacket_man_4.png"),
    "jacket_man_5": require("images/character/jacket_man_5.png"),
    "jacket_man_6": require("images/character/jacket_man_6.png"),
    "jacket_woman_1": require("images/character/jacket_woman_1.png"),
    "jacket_woman_2": require("images/character/jacket_woman_2.png"),
    "jacket_woman_3": require("images/character/jacket_woman_3.png"),
    "jacket_woman_4": require("images/character/jacket_woman_4.png"),
    "jacket_woman_5": require("images/character/jacket_woman_5.png"),
    "jacket_woman_6": require("images/character/jacket_woman_6.png"),
    "jacket_woman_7": require("images/character/jacket_woman_7.png"),


    // Lunettes
    "glasses_1": require("images/character/glasses_1.png"),
    "glasses_2": require("images/character/glasses_2.png"),
    "glasses_3": require("images/character/glasses_3.png"),
    "glasses_4": require("images/character/glasses_4.png"),
    "glasses_5": require("images/character/glasses_5.png"),


    // Cheveux
    "hair_man_1": require("images/character/hair_man_1.png"),
    "hair_man_2": require("images/character/hair_man_2.png"),
    "hair_man_3": require("images/character/hair_man_3.png"),
    "hair_man_4": require("images/character/hair_man_4.png"),
    "hair_man_5": require("images/character/hair_man_5.png"),
    "hair_man_6": require("images/character/hair_man_6.png"),
    "hair_woman_1": require("images/character/hair_woman_1.png"),
    "hair_woman_2": require("images/character/hair_woman_2.png"),
    "hair_woman_3": require("images/character/hair_woman_3.png"),
    "hair_woman_4": require("images/character/hair_woman_4.png"),
    "hair_woman_5": require("images/character/hair_woman_5.png"),
    "hair_woman_6": require("images/character/hair_woman_6.png"),
    "hair_woman_7": require("images/character/hair_woman_7.png"),
    "hair_woman_8": require("images/character/hair_woman_8.png"),

    // Personnage
    "man_1_without_face": require("images/character/man_1_without_face.png"),
    "man_2_without_face": require("images/character/man_2_without_face.png"),
    "man_3_without_face": require("images/character/man_3_without_face.png"),
    "woman_1_without_face": require("images/character/woman_1_without_face.png"),
    "woman_2_without_face": require("images/character/woman_2_without_face.png"),
    "woman_3_without_face": require("images/character/woman_3_without_face.png"),

    // Stéthoscope
    "stetho_man": require("images/character/stetho_man.png"),
    "stetho_woman": require("images/character/stetho_woman.png"),

};
