export default {
    // Chapeau
    "hat_1": require("images/character/hat_1.png"),
    "hat_2": require("images/character/hat_2.png"),
    "hat_3": require("images/character/hat_3.png"),
    "hat_4": require("images/character/hat_4.png"),
    "hat_5": require("images/character/hat_5.png"),
    "hat_6": require("images/character/hat_6.png"),
    "hat_7": require("images/character/hat_7.png"),
    "hat_8": require("images/character/hat_8.png"),
    "hat_man_1": require("images/character/hat_man_1.png"),
    "hat_woman_1": require("images/character/hat_woman_1.png"),
    "hat_woman_2": require("images/character/hat_woman_2.png"),

    // Yeux/nez
    "nose_eyes_1": require("images/character/nose_eyes_1.png"),
    "nose_eyes_2": require("images/character/nose_eyes_2.png"),
    "nose_eyes_3": require("images/character/nose_eyes_3.png"),
    "nose_eyes_4": require("images/character/nose_eyes_4.png"),
    "nose_eyes_5": require("images/character/nose_eyes_5.png"),
    "nose_eyes_6": require("images/character/nose_eyes_6.png"),
    "nose_eyes_7": require("images/character/nose_eyes_7.png"),
    "nose_eyes_8": require("images/character/nose_eyes_8.png"),
    "nose_eyes_man_1": require("images/character/nose_eyes_man_1.png"),
    "nose_eyes_man_2": require("images/character/nose_eyes_man_2.png"),
    "nose_eyes_man_3": require("images/character/nose_eyes_man_3.png"),
    "nose_eyes_man_4": require("images/character/nose_eyes_man_4.png"),
    "nose_eyes_woman_1": require("images/character/nose_eyes_woman_1.png"),
    "nose_eyes_woman_2": require("images/character/nose_eyes_woman_2.png"),
    "nose_eyes_woman_3": require("images/character/nose_eyes_woman_3.png"),
    "nose_eyes_woman_4": require("images/character/nose_eyes_woman_4.png"),
    "nose_eyes_woman_5": require("images/character/nose_eyes_woman_5.png"),
    "nose_eyes_woman_6": require("images/character/nose_eyes_woman_6.png"),

    // Face
    "face_1": require("images/character/face_1.png"),
    "face_2": require("images/character/face_2.png"),
    "face_man_1": require("images/character/face_man_1.png"),
    "face_man_2": require("images/character/face_man_2.png"),
    "face_man_3": require("images/character/face_man_3.png"),
    "face_man_4": require("images/character/face_man_4.png"),
    "face_man_5": require("images/character/face_man_5.png"),
    "face_man_6": require("images/character/face_man_6.png"),
    "face_woman_1": require("images/character/face_woman_1.png"),
    "face_woman_2": require("images/character/face_woman_2.png"),
    "face_woman_3": require("images/character/face_woman_3.png"),
    "face_woman_4": require("images/character/face_woman_4.png"),

    // Veste
    "jacket_man_1": require("images/character/jacket_man_1.png"),
    "jacket_man_2": require("images/character/jacket_man_2.png"),
    "jacket_man_3": require("images/character/jacket_man_3.png"),
    "jacket_man_4": require("images/character/jacket_man_4.png"),
    "jacket_man_5": require("images/character/jacket_man_5.png"),
    "jacket_man_6": require("images/character/jacket_man_6.png"),
    "jacket_woman_1": require("images/character/jacket_woman_1.png"),
    "jacket_woman_2": require("images/character/jacket_woman_2.png"),
    "jacket_woman_3": require("images/character/jacket_woman_3.png"),
    "jacket_woman_4": require("images/character/jacket_woman_4.png"),
    "jacket_woman_5": require("images/character/jacket_woman_5.png"),
    "jacket_woman_6": require("images/character/jacket_woman_6.png"),
    "jacket_woman_7": require("images/character/jacket_woman_7.png"),


    // Lunettes
    "glasses_1": require("images/character/glasses_1.png"),
    "glasses_2": require("images/character/glasses_2.png"),
    "glasses_3": require("images/character/glasses_3.png"),
    "glasses_4": require("images/character/glasses_4.png"),
    "glasses_5": require("images/character/glasses_5.png"),


    // Pilosité
    // TODO Revoir image pour mettre cheveux derrière la barbe
    "pilosity_1": require("images/character/pilosity_1.png"),
    "pilosity_man_1": require("images/character/pilosity_man_1.png"),
    "pilosity_man_2": require("images/character/pilosity_man_2.png"),
    "pilosity_man_3": require("images/character/pilosity_man_3.png"),
    "pilosity_man_4": require("images/character/pilosity_man_4.png"),
    "pilosity_man_5": require("images/character/pilosity_man_5.png"),
    "pilosity_woman_1": require("images/character/pilosity_woman_1.png"),
    "pilosity_woman_2": require("images/character/pilosity_woman_2.png"),
    "pilosity_woman_3": require("images/character/pilosity_woman_3.png"),
    "pilosity_woman_4": require("images/character/pilosity_woman_4.png"),
};
